# Generated by Django 3.0 on 2019-12-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argip_id', models.CharField(default='1', max_length=100)),
                ('shop_id', models.CharField(default='1', max_length=100)),
                ('parent_category_id_argip', models.CharField(default='1', max_length=100)),
                ('parent_category_id_shop', models.CharField(default='1', max_length=100)),
            ],
        ),
    ]
