# Generated by Django 3.0 on 2019-12-12 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArgipApp', '0002_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='1', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('argip_category_id', models.CharField(default='1', max_length=10)),
                ('summary', models.CharField(default='1', max_length=50)),
                ('barcode', models.CharField(default='1', max_length=20)),
                ('count', models.IntegerField(default=0)),
                ('purchase_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='argip_id',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id_argip',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category_id_shop',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='category',
            name='shop_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
