# Generated by Django 3.0 on 2019-12-12 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArgipApp', '0003_auto_20191212_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop_category_id',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
