# Generated by Django 3.0 on 2019-12-23 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArgipApp', '0006_auto_20191222_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_updated',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
